feat: inputfield added
miproteina/gym-app pull request #17
Opened 2024-07-15 21:11 UTC by jquiceno2219

InputField added with file structure. Storybook and testing still todo.

2024-07-15 21:31 UTC, mauroziux requested changes
cambia solamente l ode la identacion sol odebes correr `yarn lintfix` so el que aparezca en el package.json

2024-07-15 21:31 UTC, mauroziux commented on app.vue
verifica que corras `yarn lintfinx` ya que esto es un problem a de identacion

2024-07-15 21:31 UTC, mauroziux commented on components/atoms/InputField/InputField.vue
> +  background-color: #f0f0f0;
recuerdfa que ya esta instalado tailwind puedes hacer uso de ello con @apply revisar documentacion

2024-07-15 21:31 UTC, mauroziux commented on pages/index.vue
> +
listo esto despues lo debes mover al login y al regisetr creoque habia creado un authform que contiene ambos seria mas util ahi de reto lo veo bien

2024-07-22 22:09 UTC, jquiceno2219 commented on components/atoms/InputField/InputField.vue
> +  background-color: #f0f0f0;
Esto lo tuve en cuenta en el más reciente commit

2024-07-22 22:09 UTC, jquiceno2219 commented
Hola mauro! Revisé los comentarios del anterior merge y agregué nuevos archivos para select y sb para input

2024-07-23 08:55 UTC, merged