PageTitle and ExerciseCard
miproteina/gym-app pull request #31
Opened 2024-08-07 17:52 UTC by valeriamg755

2024-08-07 18:12 UTC, mauroziux requested changes
**recomendaciones**:

1. separa tus ramas por objetivo de trabajo, no pongas todo en una sola rama, es decir una rama y su PR para los cambios del button component, otra para el pagetitle y otra para el exercisecard
2. sobreescribir el codigo de alguien mas debe tener una fuerte justificacion, primero deberia haber comunicacion entre ambos y ver porq es necesario los cambios en pro de agregar valor al codigo ejemplo mejoras y solucion de errores.
3. los desarrolladores son el primer filtro siempre deben revisar que su codigo este bien, (codigo duplicado) testearlo localmente y revisar que todo uncione como es esperado
4. los cambios de versiones deben tener un objetivo y deben hacerse en una rama aparte con su PR.

2024-08-07 18:12 UTC, mauroziux commented on .storybook/preview.ts
> +  const scriptNoModule = document.createElement('script')
esto esta probado localmente? los iconos

2024-08-07 18:12 UTC, mauroziux commented on components/atoms/Button/Button.vue
> +  `ion-button ${props.color}`,
i vas agregar el color como una clase debes implementar BEM

2024-08-07 18:12 UTC, mauroziux commented on components/atoms/Button/Button.vue
> +  &.primary {
no deberias remover una buena practica aca recuerda los cambios es para mejorar, aplicar BEM

2024-08-07 18:12 UTC, mauroziux commented on components/atoms/Button/Button.vue
> +  &.secondary {
no deberias remover una buena practica aca recuerda los cambios es para mejorar, aplicar BEM

2024-08-07 18:12 UTC, mauroziux commented on components/atoms/Button/Button.vue
> +  &.loading {
no deberias remover una buena practica aca recuerda los cambios es para mejorar, aplicar BEM

2024-08-07 18:12 UTC, mauroziux commented on components/atoms/Button/Button.vue
> +.spinner {
lo mismo aca no deberias remover algo que tu companero hizo, busca como adaptarlo o agregar valor al componente de el

2024-08-07 18:12 UTC, mauroziux commented on components/organisms/PageTitle/PageTitle.vue
> +        :key="index"
ya habia explicado porq no usar index como una key, revisa el canal de general

2024-08-07 18:12 UTC, mauroziux commented on components/organisms/PageTitle/PageTitle.vue
> +<script>
creo que todo esto esta repetido en las primeras lineas de este mismo archivo

2024-08-07 18:12 UTC, mauroziux commented on components/organisms/PageTitle/PageTitle.vue
> +  background-color: #f5f5f5;
color y demas deberian ser tratados como variables puedes ayudarte con pimienta para que te explique la importancia de esto.

2024-08-07 18:12 UTC, mauroziux commented on components/organisms/PageTitle/PageTitle.vue
> +      background-color: #007bff;
variable

2024-08-07 18:12 UTC, mauroziux commented on components/organisms/PageTitle/PageTitle.vue
> +<style scoped lang="scss">
esta repetido no se si son identicos o alguno es el original

2024-08-07 18:12 UTC, mauroziux commented on package.json
> +    "vitest": "^2.0.5",
alguna razon de actualizar la version?

2024-08-09 16:49 UTC, valeriamg755 commented on package.json
> +    "vitest": "^2.0.5",
Siendo sincera, la verdad no tengo idea qué hice para que se actualizara.

2024-08-14 18:43 UTC, mauroziux approved these changes

2024-08-14 18:44 UTC, merged