Add Exercise set and checkbox
miproteina/gym-app pull request #32
Opened 2024-08-07 19:00 UTC by jquiceno2219

2024-08-07 19:55 UTC, mauroziux requested changes

2024-08-07 19:55 UTC, mauroziux commented on components/atoms/Checkbox/Checkbox.vue
> +.checkbox-block__input {
super se ve que ya tienes claro BEM

2024-08-07 19:55 UTC, mauroziux commented on components/atoms/Checkbox/Checkbox.vue
> +    <label :id="labelId" :for="checkboxId" class="checkbox-block__label">{{ label }}</label>
aca deberias agregar una condicional para mostrar el label solo si existe

2024-08-07 19:55 UTC, mauroziux commented on components/atoms/InputField/InputField.vue
> +    font-size: 0.8rem; /* Smaller size for small screens */
aca tener muhco cuidado ya que al reducir la fuente cuando la pantalla sea pequena deberas hacerlo en todo los demas componentes para que sea estandar

2024-08-07 19:55 UTC, mauroziux commented on components/atoms/Select/Select.vue
> +      this.$emit('change', event.target.selectedValue)
✅ super esto reduce deuda tecnica

2024-08-07 19:55 UTC, mauroziux commented on components/atoms/Select/Select.stories.js
> -  argTypes: {
no se si sea buena idea quitar los controles, me gustaria desde la storories agregar elementos o deshabilitar el select por ejemplo

2024-08-07 19:55 UTC, mauroziux commented on components/molecules/ExerciseSetActive/ExerciseSetActive.vue
> +    <Input v-model="firstNumber" :disabled="!edit" type="number" placeholder="Set" />
aca me acorde de algo el imput recibe decimales? como puedo decirle al input que si recibe un numero como valor le puedo mandar un argumento steps para incrementar el numero cada 0.5 o cada 1?

esto no esta en nigun ticket pero se debe implementar ya que algunos input recibiran peso en kilos y en libras y se requiere decimales para ello osea puedo cargar 12.5kg en una barra pero puedo hacer en otro input repeticiones de la serie que ese nunca iria con decimales.

2024-08-07 19:57 UTC, jquiceno2219 commented on components/atoms/Select/Select.stories.js
> -  argTypes: {
Entiendo. Vi que quitarlo no hacía ningún cambio visual, así que supuse que no habría problema, pero si esto es lo que habilita los controles, los volveré a poner en el siguiente PR :D.

2024-08-08 21:11 UTC, jquiceno2219 commented on components/molecules/ExerciseSetActive/ExerciseSetActive.vue
> +    <Input v-model="firstNumber" :disabled="!edit" type="number" placeholder="Set" />
Agregado en el nuevo commit

2024-08-09 16:25 UTC, mauroziux approved these changes
no vi donde agregaste los steps de los input, tambien debes agregar pruebas unitarias para validar esa condicion

2024-08-09 16:26 UTC, merged