Add ExerciseActiveList, and uptade setActive CSS to match with header.
miproteina/gym-app pull request #34
Opened 2024-08-12 22:19 UTC by jquiceno2219

2024-08-13 22:16 UTC, mauroziux requested changes

2024-08-13 22:16 UTC, mauroziux commented on components/organisms/ExerciseList/ExerciseActiveList.vue
> +          v-model:modelChecked="exercise.checked"
deberias pasar mejor un objecto en este caso el exercise completo y puedes syncronizarlos con sync emitiendo un update desde el childelement

2024-08-14 18:24 UTC, jquiceno2219 commented on components/organisms/ExerciseList/ExerciseActiveList.vue
> +          :exercise="exercise"
Pasa el objeto, no las propiedades

2024-08-14 18:45 UTC, mauroziux approved these changes

2024-08-14 19:19 UTC, merged